language: java
jdk:
- openjdk8
script:
- "./gradlew clean build"
- export RELEASE_NUMBER=1
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./deploy/prepare-release.sh; fi
env:
  global:
    secure: MInzfOY4TXEMmBBkXO27V9WxLU+LQfBPltIaSZBuTSBtFTDeWpNAvYenSVBKrltBtblMoqULPe7Ypk2j+eEvgadb5NDY4WO6f1vA/7uR794jUEydNEkf2I8ckEPG4+J2JVbuqwAxzAuCqt/dmFm7h9zGN9jIxgZrTQ/6iRkwx3RigBgUtGzo3/Sq9mNCTvzmOsMUH4pwlD6DwRQ7F+wF1BeZ3pp/TratY7J+VjC9/QAMTA+zS5pKzbhfgFBrBRqgP0/OgITBbV/hulHxXaHsZc2slwdG/vdjmFJnw4/FsCyNL/3Oi0IAYIu+vT9Az5bkRTQ9ZJRkA6WpQB836ON9PMxtii43d3qnKgMSyRp9Wpv3/Zyh9rQLDtEFE6qGwyHTCt8Ai0BIt59sMjds28bphB5NlwUOXCRACBcDGYlfNQBWIZ3Akb1xeU31EZZd9jDclxxOc416ndNxN2fMuFajXAFtq3SfrldCbeWCBMKks22+i4PnfEMaWb+o6mvS9puyhyGNgtdMSSXaiJvZfbK8ZE+fuVtrMzvK2BRBwB8U5vVjIeMsnVWC7AK3+cYaxS0Mu9jTIDPSZkYfeiWlvMXpdvcI39l1V/BW60aVlEaylS3lPO/8MNZVqWjA2ZnK0tkX/bwGQumpd3IuMwx0nPOEh+Zzyaf9R/Kz3hMGDE3J8ek=
